-- AWL-based IELTS core vocabulary seed data
INSERT INTO word (word, phonetic, meaning, example, category) VALUES
('analyse', '/ˈænəlaɪz/', '分析', 'Researchers analyse the data before drawing conclusions.', 'academic'),
('approach', '/əˈprəʊtʃ/', '方法；接近', 'A new approach to teaching writing was introduced.', 'academic'),
('area', '/ˈeəriə/', '领域；地区', 'This area of research is still developing.', 'academic'),
('assess', '/əˈses/', '评估', 'Teachers assess students through essays and exams.', 'education'),
('assume', '/əˈsjuːm/', '假设', 'We cannot assume that all learners have the same background.', 'academic'),
('authority', '/ɔːˈθɒrəti/', '权威；当局', 'The local authority funded the new library.', 'society'),
('available', '/əˈveɪləbl/', '可获得的', 'Past papers are available on the website.', 'academic'),
('benefit', '/ˈbenɪfɪt/', '益处', 'Regular reading is a clear benefit for vocabulary growth.', 'academic'),
('concept', '/ˈkɒnsept/', '概念', 'The concept of sustainability appears in many essays.', 'academic'),
('consist', '/kənˈsɪst/', '由…组成', 'The test consists of four sections.', 'academic'),
('constitute', '/ˈkɒnstɪtjuːt/', '构成', 'These factors constitute a major challenge.', 'academic'),
('context', '/ˈkɒntekst/', '语境；背景', 'Always guess meaning from context first.', 'academic'),
('contract', '/ˈkɒntrækt/', '合同', 'The company signed a contract with the university.', 'economy'),
('create', '/kriˈeɪt/', '创造', 'Good examples create a stronger argument.', 'academic'),
('data', '/ˈdeɪtə/', '数据', 'The data show a steady increase in scores.', 'academic'),
('define', '/dɪˈfaɪn/', '定义', 'The author defines key terms in the introduction.', 'academic'),
('derive', '/dɪˈraɪv/', '源自', 'Many English academic words derive from Latin.', 'academic'),
('distribute', '/dɪˈstrɪbjuːt/', '分配', 'Resources are not evenly distributed.', 'economy'),
('economy', '/ɪˈkɒnəmi/', '经济', 'Tourism is important to the local economy.', 'economy'),
('environment', '/ɪnˈvaɪrənmənt/', '环境', 'Protecting the environment is a common IELTS topic.', 'environment'),
('establish', '/ɪˈstæblɪʃ/', '建立', 'The school was established in 1998.', 'academic'),
('estimate', '/ˈestɪmeɪt/', '估计', 'Experts estimate that demand will rise.', 'academic'),
('evident', '/ˈevɪdənt/', '明显的', 'It is evident that practice improves fluency.', 'academic'),
('export', '/ˈekspɔːt/', '出口', 'The country exports agricultural products.', 'economy'),
('factor', '/ˈfæktə/', '因素', 'Motivation is a key factor in language learning.', 'academic'),
('finance', '/ˈfaɪnæns/', '财政；资助', 'Students may need finance for overseas study.', 'economy'),
('formula', '/ˈfɔːmjələ/', '公式；方案', 'There is no single formula for a high band score.', 'academic'),
('function', '/ˈfʌŋkʃn/', '功能', 'The main function of an introduction is to outline the topic.', 'academic'),
('identify', '/aɪˈdentɪfaɪ/', '识别', 'Identify the writer''s opinion before answering.', 'academic'),
('income', '/ˈɪnkʌm/', '收入', 'Average income has increased in cities.', 'economy'),
('indicate', '/ˈɪndɪkeɪt/', '表明', 'The graph indicates a sharp decline.', 'academic'),
('individual', '/ˌɪndɪˈvɪdʒuəl/', '个人；个别的', 'Each individual has a different learning style.', 'society'),
('interpret', '/ɪnˈtɜːprɪt/', '解释', 'Candidates must interpret charts in Task 1.', 'academic'),
('involve', '/ɪnˈvɒlv/', '涉及', 'The process involves several stages.', 'academic'),
('issue', '/ˈɪʃuː/', '问题', 'Climate change is a global issue.', 'society'),
('labour', '/ˈleɪbə/', '劳动', 'The labour market is becoming more competitive.', 'economy'),
('legal', '/ˈliːɡl/', '法律的', 'There are legal limits on working hours.', 'society'),
('legislate', '/ˈledʒɪsleɪt/', '立法', 'Governments legislate to protect consumers.', 'society'),
('major', '/ˈmeɪdʒə/', '主要的', 'Traffic congestion is a major problem.', 'society'),
('method', '/ˈmeθəd/', '方法', 'This method is widely used in research.', 'academic'),
('occur', '/əˈkɜː/', '发生', 'Most errors occur under time pressure.', 'academic'),
('percent', '/pəˈsent/', '百分之…', 'Unemployment fell by three percent.', 'economy'),
('period', '/ˈpɪəriəd/', '时期', 'Over a ten-year period, sales doubled.', 'academic'),
('policy', '/ˈpɒləsi/', '政策', 'Education policy varies from country to country.', 'society'),
('principle', '/ˈprɪnsəpl/', '原则', 'Fairness is a basic principle of assessment.', 'academic'),
('proceed', '/prəˈsiːd/', '继续进行', 'The discussion will proceed to the next topic.', 'academic'),
('process', '/ˈprəʊses/', '过程', 'Recycling is a complex process.', 'environment'),
('require', '/rɪˈkwaɪə/', '需要', 'Task 2 requires at least 250 words.', 'academic'),
('research', '/rɪˈsɜːtʃ/', '研究', 'Further research is needed.', 'academic'),
('respond', '/rɪˈspɒnd/', '回应', 'Companies must respond to customer complaints.', 'society'),
('role', '/rəʊl/', '角色', 'Parents play an important role in education.', 'education'),
('section', '/ˈsekʃn/', '部分', 'Complete this section of the form.', 'academic'),
('sector', '/ˈsektə/', '部门；行业', 'The public sector employs many graduates.', 'economy'),
('significant', '/sɪɡˈnɪfɪkənt/', '显著的', 'There was a significant improvement.', 'academic'),
('similar', '/ˈsɪmələ/', '相似的', 'The two charts show similar trends.', 'academic'),
('source', '/sɔːs/', '来源', 'Always check the source of information.', 'academic'),
('specific', '/spəˈsɪfɪk/', '具体的', 'Give specific examples in your essay.', 'academic'),
('structure', '/ˈstrʌktʃə/', '结构', 'A clear structure helps the examiner.', 'academic'),
('theory', '/ˈθɪəri/', '理论', 'The theory is supported by evidence.', 'academic'),
('vary', '/ˈveəri/', '变化', 'Scores vary from candidate to candidate.', 'academic'),
('achieve', '/əˈtʃiːv/', '达到', 'She achieved a band 7 in writing.', 'education'),
('acquire', '/əˈkwaɪə/', '获得', 'Children acquire language naturally.', 'education'),
('administrate', '/ədˈmɪnɪstreɪt/', '管理', 'The office administrates student records.', 'society'),
('affect', '/əˈfekt/', '影响', 'Sleep can affect exam performance.', 'health'),
('appropriate', '/əˈprəʊpriət/', '合适的', 'Use an appropriate academic tone.', 'academic'),
('aspect', '/ˈæspekt/', '方面', 'One aspect of the problem is cost.', 'academic'),
('assist', '/əˈsɪst/', '帮助', 'Teachers assist students with planning.', 'education'),
('category', '/ˈkætəɡəri/', '类别', 'Words are grouped by category.', 'academic'),
('chapter', '/ˈtʃæptə/', '章节', 'Read the first chapter before class.', 'education'),
('commission', '/kəˈmɪʃn/', '委托；委员会', 'A report was commissioned by the government.', 'society'),
('community', '/kəˈmjuːnəti/', '社区', 'The community supports local schools.', 'society'),
('complex', '/ˈkɒmpleks/', '复杂的', 'It is a complex issue with no simple answer.', 'academic'),
('compute', '/kəmˈpjuːt/', '计算', 'The software can compute the results quickly.', 'technology'),
('conclude', '/kənˈkluːd/', '得出结论', 'We can conclude that practice is essential.', 'academic'),
('conduct', '/kənˈdʌkt/', '进行', 'Scientists conducted an experiment.', 'academic'),
('consequent', '/ˈkɒnsɪkwənt/', '随之发生的', 'The consequent delay affected the schedule.', 'academic'),
('construct', '/kənˈstrʌkt/', '建造；构建', 'Students construct arguments with evidence.', 'academic'),
('consume', '/kənˈsjuːm/', '消耗', 'Cities consume large amounts of energy.', 'environment'),
('credit', '/ˈkredɪt/', '学分；信用', 'He received credit for the research.', 'education'),
('culture', '/ˈkʌltʃə/', '文化', 'Culture influences communication styles.', 'culture'),
('design', '/dɪˈzaɪn/', '设计', 'The course is designed for beginners.', 'education'),
('distinct', '/dɪˈstɪŋkt/', '明显不同的', 'Task 1 and Task 2 have distinct requirements.', 'academic'),
('element', '/ˈelɪmənt/', '要素', 'Coherence is a key element of writing.', 'academic'),
('equate', '/ɪˈkweɪt/', '等同', 'Do not equate fluency with accuracy.', 'academic'),
('evaluate', '/ɪˈvæljueɪt/', '评价', 'Examiners evaluate four marking criteria.', 'education'),
('feature', '/ˈfiːtʃə/', '特征', 'Select the main features of the chart.', 'academic'),
('final', '/ˈfaɪnl/', '最终的', 'The final paragraph should restate your view.', 'academic'),
('focus', '/ˈfəʊkəs/', '关注', 'Focus on the question, not memorised essays.', 'education'),
('impact', '/ˈɪmpækt/', '影响', 'The policy had a positive impact.', 'society'),
('injure', '/ˈɪndʒə/', '伤害', 'Poor air quality may injure public health.', 'health'),
('institute', '/ˈɪnstɪtjuːt/', '机构', 'The research institute published the findings.', 'education'),
('invest', '/ɪnˈvest/', '投资', 'Governments should invest in public transport.', 'economy'),
('item', '/ˈaɪtəm/', '项目', 'Each item in the list needs an example.', 'academic'),
('journal', '/ˈdʒɜːnl/', '期刊', 'The article appeared in an academic journal.', 'academic'),
('maintain', '/meɪnˈteɪn/', '维持', 'It is hard to maintain motivation.', 'education'),
('normal', '/ˈnɔːml/', '正常的', 'Nervousness before a test is normal.', 'health'),
('obtain', '/əbˈteɪn/', '获得', 'Students hope to obtain a high score.', 'education'),
('participate', '/pɑːˈtɪsɪpeɪt/', '参与', 'Learners should participate in discussions.', 'education'),
('perceive', '/pəˈsiːv/', '察觉；认为', 'Some people perceive online classes as less effective.', 'education'),
('positive', '/ˈpɒzətɪv/', '积极的', 'There are positive effects of remote work.', 'society'),
('potential', '/pəˈtenʃl/', '潜在的', 'AI has the potential to support learners.', 'technology'),
('previous', '/ˈpriːviəs/', '之前的', 'Learn from previous mistakes.', 'academic'),
('primary', '/ˈpraɪməri/', '主要的；初级的', 'The primary aim is to improve coherence.', 'academic'),
('purchase', '/ˈpɜːtʃəs/', '购买', 'Consumers purchase goods online.', 'economy'),
('range', '/reɪndʒ/', '范围', 'Use a wide range of vocabulary.', 'academic'),
('region', '/ˈriːdʒən/', '地区', 'The region suffers from water shortages.', 'environment'),
('regulate', '/ˈreɡjuleɪt/', '监管', 'Advertising to children should be regulated.', 'society'),
('relevant', '/ˈreləvənt/', '相关的', 'Only include relevant ideas.', 'academic'),
('reside', '/rɪˈzaɪd/', '居住', 'Many graduates reside in large cities.', 'society'),
('resource', '/rɪˈsɔːs/', '资源', 'Time is a limited resource in the exam.', 'academic'),
('restrict', '/rɪˈstrɪkt/', '限制', 'Some countries restrict car use in city centres.', 'environment'),
('secure', '/sɪˈkjʊə/', '安全的；获得', 'A degree can help secure a better job.', 'economy'),
('seek', '/siːk/', '寻求', 'Candidates seek reliable practice materials.', 'education'),
('select', '/sɪˈlekt/', '选择', 'Select and report the main features.', 'academic'),
('site', '/saɪt/', '地点', 'The university site is close to the station.', 'society'),
('strategy', '/ˈstrætədʒi/', '策略', 'A revision strategy should include mock tests.', 'education'),
('survey', '/ˈsɜːveɪ/', '调查', 'The survey found that most students prefer evening classes.', 'academic'),
('text', '/tekst/', '文本', 'Highlight keywords in the reading text.', 'academic'),
('tradition', '/trəˈdɪʃn/', '传统', 'Some traditions are disappearing in cities.', 'culture'),
('transfer', '/trænsˈfɜː/', '转移', 'Skills can transfer from speaking to writing.', 'education'),
('alternative', '/ɔːlˈtɜːnətɪv/', '替代的', 'Public transport is an alternative to driving.', 'environment'),
('circumstance', '/ˈsɜːkəmstəns/', '情况', 'Under some circumstances, working from home is difficult.', 'society'),
('comment', '/ˈkɒment/', '评论', 'The teacher wrote a detailed comment.', 'education'),
('compensate', '/ˈkɒmpenseɪt/', '补偿', 'Higher pay may compensate for long hours.', 'economy'),
('component', '/kəmˈpəʊnənt/', '组成部分', 'Grammar is only one component of writing.', 'academic'),
('consent', '/kənˈsent/', '同意', 'Participants gave their consent.', 'academic'),
('considerable', '/kənˈsɪdərəbl/', '相当大的', 'There has been a considerable rise in prices.', 'economy'),
('constant', '/ˈkɒnstənt/', '持续的', 'Constant practice is more useful than last-minute study.', 'education'),
('constrain', '/kənˈstreɪn/', '限制', 'A small budget can constrain research.', 'academic'),
('contribute', '/kənˈtrɪbjuːt/', '贡献', 'Volunteers contribute to community projects.', 'society'),
('convene', '/kənˈviːn/', '召集', 'The committee will convene next week.', 'society'),
('coordinate', '/kəʊˈɔːdɪneɪt/', '协调', 'Schools coordinate with parents.', 'education'),
('core', '/kɔː/', '核心', 'These are core academic words.', 'academic'),
('corporate', '/ˈkɔːpərət/', '公司的', 'Corporate sponsorship funded the event.', 'economy'),
('correspond', '/ˌkɒrəˈspɒnd/', '相应；通信', 'The figures correspond to the table.', 'academic'),
('criteria', '/kraɪˈtɪəriə/', '标准', 'IELTS writing has four criteria.', 'education'),
('deduce', '/dɪˈdjuːs/', '推断', 'Readers must deduce the writer''s attitude.', 'academic'),
('demonstrate', '/ˈdemənstreɪt/', '证明；演示', 'Examples demonstrate your lexical resource.', 'academic'),
('document', '/ˈdɒkjumənt/', '文件；记录', 'Please document your sources.', 'academic'),
('dominate', '/ˈdɒmɪneɪt/', '主导', 'Private cars still dominate urban transport.', 'society'),
('emphasis', '/ˈemfəsɪs/', '强调', 'Place emphasis on task response.', 'academic'),
('ensure', '/ɪnˈʃʊə/', '确保', 'Ensure that every paragraph has a topic sentence.', 'academic'),
('exclude', '/ɪkˈskluːd/', '排除', 'Do not exclude opposing views in a discussion essay.', 'academic'),
('framework', '/ˈfreɪmwɜːk/', '框架', 'Use a simple framework for Task 2.', 'academic'),
('fund', '/fʌnd/', '资金；资助', 'The project is funded by the government.', 'economy'),
('illustrate', '/ˈɪləstreɪt/', '说明', 'A chart can illustrate the trend clearly.', 'academic'),
('immigrate', '/ˈɪmɪɡreɪt/', '移居入境', 'Many skilled workers immigrate for better jobs.', 'society'),
('imply', '/ɪmˈplaɪ/', '暗示', 'The writer implies that the policy failed.', 'academic'),
('initial', '/ɪˈnɪʃl/', '最初的', 'The initial results were promising.', 'academic'),
('instance', '/ˈɪnstəns/', '例子', 'For instance, cycling reduces congestion.', 'academic'),
('interact', '/ˌɪntərˈækt/', '互动', 'Students interact more in small classes.', 'education'),
('justify', '/ˈdʒʌstɪfaɪ/', '证明…合理', 'Justify your opinion with reasons.', 'academic'),
('layer', '/ˈleɪə/', '层次', 'The argument has several layers.', 'academic'),
('link', '/lɪŋk/', '联系', 'Link ideas with cohesive devices.', 'academic'),
('locate', '/ləʊˈkeɪt/', '定位', 'Locate the relevant paragraph quickly.', 'academic'),
('maximise', '/ˈmæksɪmaɪz/', '最大化', 'Maximise your score with careful planning.', 'education'),
('minor', '/ˈmaɪnə/', '较小的', 'A minor error will not ruin a band 7 essay.', 'academic'),
('negate', '/nɪˈɡeɪt/', '否定', 'One weak paragraph can negate an otherwise clear argument.', 'academic'),
('outcome', '/ˈaʊtkʌm/', '结果', 'The outcome depends on consistent practice.', 'education'),
('partner', '/ˈpɑːtnə/', '伙伴', 'Find a speaking partner if possible.', 'education'),
('philosophy', '/fəˈlɒsəfi/', '哲学；理念', 'The school''s philosophy emphasises independence.', 'education'),
('physical', '/ˈfɪzɪkl/', '身体的；物质的', 'Physical activity supports mental health.', 'health'),
('proportion', '/prəˈpɔːʃn/', '比例', 'A large proportion of students study abroad.', 'academic'),
('publish', '/ˈpʌblɪʃ/', '发表', 'The results were published last year.', 'academic'),
('react', '/riˈækt/', '反应', 'Markets react quickly to new policies.', 'economy'),
('register', '/ˈredʒɪstə/', '登记', 'Please register for the mock test.', 'education'),
('rely', '/rɪˈlaɪ/', '依赖', 'Do not rely on memorised templates.', 'education'),
('remove', '/rɪˈmuːv/', '移除', 'Remove irrelevant sentences.', 'academic'),
('scheme', '/skiːm/', '计划', 'A recycling scheme was introduced.', 'environment'),
('sequence', '/ˈsiːkwəns/', '顺序', 'Describe the sequence of stages in a process.', 'academic'),
('sex', '/seks/', '性别', 'The table compares results by age and sex.', 'society'),
('shift', '/ʃɪft/', '转变', 'There has been a shift towards online learning.', 'education'),
('specify', '/ˈspesɪfaɪ/', '明确说明', 'Specify the time period shown in the graph.', 'academic'),
('sufficient', '/səˈfɪʃnt/', '足够的', 'Task 1 needs sufficient data comparison.', 'academic'),
('task', '/tɑːsk/', '任务', 'Complete the task within 40 minutes.', 'education'),
('technical', '/ˈteknɪkl/', '技术的', 'Avoid overly technical language in Task 2.', 'technology'),
('technique', '/tekˈniːk/', '技巧', 'Skimming is a useful reading technique.', 'education'),
('technology', '/tekˈnɒlədʒi/', '技术', 'Technology has changed how people work.', 'technology'),
('valid', '/ˈvælɪd/', '有效的', 'Is this argument valid?', 'academic'),
('volume', '/ˈvɒljuːm/', '量；册', 'The volume of traffic increased.', 'society'),
('access', '/ˈækses/', '进入；使用权', 'Not everyone has access to high-quality education.', 'education'),
('adequate', '/ˈædɪkwət/', '足够的', 'The sample size was not adequate.', 'academic'),
('annual', '/ˈænjuəl/', '每年的', 'The annual report was released in March.', 'economy'),
('apparent', '/əˈpærənt/', '显而易见的', 'The difference is apparent in the second chart.', 'academic'),
('approximate', '/əˈprɒksɪmət/', '大约的', 'The figure is approximate, not exact.', 'academic'),
('attitude', '/ˈætɪtjuːd/', '态度', 'The writer''s attitude is critical.', 'academic'),
('attribute', '/əˈtrɪbjuːt/', '归因于', 'They attribute the rise to better healthcare.', 'health'),
('civil', '/ˈsɪvl/', '公民的', 'Civil society organisations campaigned for change.', 'society'),
('code', '/kəʊd/', '规范；代码', 'There is a professional code of conduct.', 'society'),
('commit', '/kəˈmɪt/', '承诺；投入', 'Governments must commit resources to education.', 'education'),
('communicate', '/kəˈmjuːnɪkeɪt/', '交流', 'Learners need to communicate ideas clearly.', 'education'),
('concentrate', '/ˈkɒnsntreɪt/', '集中', 'It is hard to concentrate in a noisy room.', 'education'),
('confer', '/kənˈfɜː/', '授予；商讨', 'The degree was conferred last summer.', 'education'),
('contrast', '/ˈkɒntrɑːst/', '对比', 'In contrast, rural areas grew more slowly.', 'academic'),
('cycle', '/ˈsaɪkl/', '循环', 'The diagram shows the water cycle.', 'environment'),
('debate', '/dɪˈbeɪt/', '辩论', 'There is an ongoing debate about homework.', 'education'),
('despite', '/dɪˈspaɪt/', '尽管', 'Despite the cost, many families travel abroad.', 'academic'),
('dimension', '/daɪˈmenʃn/', '方面；维度', 'The problem has an economic dimension.', 'academic'),
('domestic', '/dəˈmestɪk/', '国内的；家庭的', 'Domestic energy use has increased.', 'environment'),
('emerge', '/ɪˈmɜːdʒ/', '出现', 'New industries have emerged.', 'economy'),
('error', '/ˈerə/', '错误', 'A small grammatical error is acceptable at band 7.', 'education'),
('ethnic', '/ˈeθnɪk/', '民族的', 'The city has a diverse ethnic population.', 'culture'),
('goal', '/ɡəʊl/', '目标', 'Set a realistic band score goal.', 'education'),
('grant', '/ɡrɑːnt/', '授予；拨款', 'The student received a research grant.', 'education'),
('hence', '/hens/', '因此', 'The trend is downward; hence the forecast is pessimistic.', 'academic'),
('hypothesis', '/haɪˈpɒθəsɪs/', '假设', 'The hypothesis was tested in two experiments.', 'academic'),
('implement', '/ˈɪmplɪment/', '实施', 'It is easier to propose a policy than to implement it.', 'society'),
('implicate', '/ˈɪmplɪkeɪt/', '牵涉', 'Several factors are implicated in the decline.', 'academic'),
('impose', '/ɪmˈpəʊz/', '强加', 'The city imposed a congestion charge.', 'society'),
('integrate', '/ˈɪntɪɡreɪt/', '整合', 'Integrate examples into your argument.', 'academic'),
('internal', '/ɪnˈtɜːnl/', '内部的', 'Internal motivation lasts longer.', 'education'),
('investigate', '/ɪnˈvestɪɡeɪt/', '调查', 'Scientists investigated the cause of the outbreak.', 'health'),
('job', '/dʒɒb/', '工作', 'A degree does not guarantee a job.', 'economy'),
('label', '/ˈleɪbl/', '标签', 'Label the axes of the graph clearly.', 'academic'),
('mechanism', '/ˈmekənɪzəm/', '机制', 'The mechanism of heat reduction is shade from trees.', 'environment'),
('obvious', '/ˈɒbviəs/', '明显的', 'The most obvious trend is growth in Asia.', 'academic'),
('occupy', '/ˈɒkjupaɪ/', '占用', 'Agriculture occupies most of the land.', 'environment'),
('option', '/ˈɒpʃn/', '选择', 'One option is to raise fuel taxes.', 'society'),
('output', '/ˈaʊtpʊt/', '产量', 'Factory output declined in winter.', 'economy'),
('overall', '/ˌəʊvərˈɔːl/', '总体的', 'Overall, the number of users rose.', 'academic'),
('parallel', '/ˈpærəlel/', '平行的；相似的', 'There is a parallel trend in both countries.', 'academic'),
('parameter', '/pəˈræmɪtə/', '参数', 'Age was an important parameter in the study.', 'academic'),
('phase', '/feɪz/', '阶段', 'The project is still in its early phase.', 'academic'),
('predict', '/prɪˈdɪkt/', '预测', 'It is difficult to predict future energy demand.', 'environment'),
('principal', '/ˈprɪnsəpl/', '主要的', 'The principal reason is cost.', 'academic'),
('prior', '/ˈpraɪə/', '先前的', 'Prior knowledge helps in reading tests.', 'education'),
('professional', '/prəˈfeʃənl/', '专业的', 'Professional training can improve job prospects.', 'economy'),
('project', '/ˈprɒdʒekt/', '项目；预测', 'The chart projects population growth.', 'academic'),
('promote', '/prəˈməʊt/', '促进', 'Campaigns promote healthy eating.', 'health'),
('regime', '/reɪˈʒiːm/', '体制；制度', 'A new tax regime was introduced.', 'society'),
('resolve', '/rɪˈzɒlv/', '解决', 'Talks failed to resolve the dispute.', 'society'),
('retain', '/rɪˈteɪn/', '保留', 'It is hard to retain new vocabulary without review.', 'education'),
('series', '/ˈsɪəriːz/', '系列', 'The line graph shows a series of changes.', 'academic'),
('statistic', '/stəˈtɪstɪk/', '统计数据', 'Quote one statistic, not too many.', 'academic'),
('status', '/ˈsteɪtəs/', '地位；状态', 'Social status can affect educational opportunity.', 'society'),
('stress', '/stres/', '压力', 'Exam stress is common among teenagers.', 'health'),
('subsequent', '/ˈsʌbsɪkwənt/', '随后的', 'Subsequent studies confirmed the result.', 'academic'),
('sum', '/sʌm/', '总和', 'The sum of the four scores is averaged.', 'education'),
('summary', '/ˈsʌməri/', '摘要', 'Write a summary of the main trends.', 'academic'),
('undertake', '/ˌʌndəˈteɪk/', '承担；进行', 'The university will undertake a review.', 'academic'),
('abandon', '/əˈbændən/', '放弃', 'Do not abandon a paragraph halfway.', 'academic'),
('adapt', '/əˈdæpt/', '适应', 'Workers must adapt to new technology.', 'technology'),
('adult', '/ˈædʌlt/', '成年人', 'Adult learners often have clearer goals.', 'education'),
('advocate', '/ˈædvəkeɪt/', '提倡', 'Some experts advocate shorter working weeks.', 'society'),
('aid', '/eɪd/', '帮助', 'Visual aids can support a presentation.', 'education'),
('channel', '/ˈtʃænl/', '渠道', 'Social media is a major news channel.', 'society'),
('chemical', '/ˈkemɪkl/', '化学物质', 'Chemical pollution affects rivers.', 'environment'),
('classic', '/ˈklæsɪk/', '经典的', 'This is a classic Task 2 discussion question.', 'education'),
('comprehensive', '/ˌkɒmprɪˈhensɪv/', '全面的', 'A comprehensive plan is needed.', 'academic'),
('comprise', '/kəmˈpraɪz/', '包括', 'The exam comprises four papers.', 'education'),
('confirm', '/kənˈfɜːm/', '确认', 'Later data confirmed the trend.', 'academic'),
('contrary', '/ˈkɒntrəri/', '相反的', 'On the contrary, rural income grew slowly.', 'academic'),
('convert', '/kənˈvɜːt/', '转变', 'Waste heat can be converted into electricity.', 'environment'),
('couple', '/ˈkʌpl/', '几个；一对', 'The figure rose for a couple of years.', 'academic'),
('decade', '/ˈdekeɪd/', '十年', 'Over the decade, internet use soared.', 'society'),
('definite', '/ˈdefɪnət/', '明确的', 'Give a definite opinion in the conclusion.', 'academic'),
('deny', '/dɪˈnaɪ/', '否认', 'Few would deny the value of education.', 'academic'),
('differentiate', '/ˌdɪfəˈrenʃieɪt/', '区分', 'Differentiate between facts and opinions.', 'academic'),
('dispose', '/dɪˈspəʊz/', '处理', 'How should cities dispose of plastic waste?', 'environment'),
('dynamic', '/daɪˈnæmɪk/', '动态的', 'The job market is highly dynamic.', 'economy'),
('eliminate', '/ɪˈlɪmɪneɪt/', '消除', 'It is unrealistic to eliminate all traffic.', 'society'),
('empirical', '/ɪmˈpɪrɪkl/', '实证的', 'The claim lacks empirical support.', 'academic'),
('equip', '/ɪˈkwɪp/', '装备', 'Schools should equip students with digital skills.', 'education'),
('extract', '/ˈekstrækt/', '提取', 'Extract the main idea from each paragraph.', 'academic'),
('file', '/faɪl/', '文件；提交', 'Please file your application online.', 'society'),
('finite', '/ˈfaɪnaɪt/', '有限的', 'Oil is a finite resource.', 'environment'),
('foundation', '/faʊnˈdeɪʃn/', '基础', 'Vocabulary is the foundation of reading.', 'education'),
('global', '/ˈɡləʊbl/', '全球的', 'This is a global challenge.', 'society'),
('grade', '/ɡreɪd/', '等级', 'The essay was given a high grade.', 'education'),
('guarantee', '/ˌɡærənˈtiː/', '保证', 'Hard work does not guarantee a band 8.', 'education'),
('hierarchy', '/ˈhaɪərɑːki/', '等级制度', 'Large companies often have a clear hierarchy.', 'economy'),
('identical', '/aɪˈdentɪkl/', '完全相同的', 'The two charts are not identical.', 'academic'),
('ideology', '/ˌaɪdiˈɒlədʒi/', '意识形态', 'The policy reflects a particular ideology.', 'society'),
('infer', '/ɪnˈfɜː/', '推断', 'Readers must infer the meaning.', 'academic'),
('innovate', '/ˈɪnəveɪt/', '创新', 'Firms that innovate tend to grow faster.', 'technology'),
('insert', '/ɪnˈsɜːt/', '插入', 'Insert a topic sentence at the start.', 'academic'),
('intervene', '/ˌɪntəˈviːn/', '干预', 'Should governments intervene in housing markets?', 'society'),
('isolate', '/ˈaɪsəleɪt/', '隔离', 'Do not isolate examples from the argument.', 'academic'),
('media', '/ˈmiːdiə/', '媒体', 'The media influence public opinion.', 'society'),
('mode', '/məʊd/', '方式', 'The most common mode of travel is by car.', 'society'),
('paradigm', '/ˈpærədaɪm/', '范式', 'Online learning represents a new paradigm.', 'education'),
('phenomenon', '/fəˈnɒmɪnən/', '现象', 'Urbanisation is a worldwide phenomenon.', 'society'),
('priority', '/praɪˈɒrəti/', '优先事项', 'Public health should be a priority.', 'health'),
('prohibit', '/prəˈhɪbɪt/', '禁止', 'Some cities prohibit smoking indoors.', 'health'),
('publication', '/ˌpʌblɪˈkeɪʃn/', '出版物', 'The publication summarises recent findings.', 'academic'),
('quotation', '/kwəʊˈteɪʃn/', '引语', 'Avoid long quotations in IELTS essays.', 'academic'),
('release', '/rɪˈliːs/', '发布；释放', 'The government released new figures.', 'society'),
('reverse', '/rɪˈvɜːs/', '逆转', 'The trend reversed after 2015.', 'academic'),
('simulate', '/ˈsɪmjuleɪt/', '模拟', 'A mock test can simulate exam conditions.', 'education'),
('sole', '/səʊl/', '唯一的', 'Cost is not the sole factor.', 'academic'),
('somewhat', '/ˈsʌmwɒt/', '有点', 'The results are somewhat surprising.', 'academic'),
('submit', '/səbˈmɪt/', '提交', 'Submit your essay before the deadline.', 'education'),
('successor', '/səkˈsesə/', '继任者', 'The successor continued the same policy.', 'society'),
('survive', '/səˈvaɪv/', '生存', 'Small shops struggle to survive.', 'economy'),
('thesis', '/ˈθiːsɪs/', '论文；论点', 'State your thesis in the introduction.', 'academic'),
('topic', '/ˈtɒpɪk/', '话题', 'Choose a relevant topic sentence.', 'academic'),
('transmit', '/trænsˈmɪt/', '传播', 'Information is transmitted instantly online.', 'technology'),
('ultimate', '/ˈʌltɪmət/', '最终的', 'The ultimate goal is independent learning.', 'education'),
('unique', '/juˈniːk/', '独特的', 'Each city faces unique challenges.', 'society'),
('visible', '/ˈvɪzəbl/', '可见的', 'The change is clearly visible in the graph.', 'academic'),
('voluntary', '/ˈvɒləntri/', '自愿的', 'Voluntary work can build experience.', 'society'),
('welfare', '/ˈwelfeə/', '福利', 'The welfare system supports low-income families.', 'society');
-- total words: 302
